app:
  postgres:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    schema: ${DATABASE_SCHEMA}
    url: ${DATASOURCE_BASEURL}
  shutdown-timeout: ${GRACEFUL_SHUTDOWN_TIMEOUT:10}
  connection-timeout: ${SPRING_CONNECTION_TIMEOUT:30s}
  telegram:
    bot:
      name: ${TELEGRAM_BOT_NAME}
      token: ${TELEGRAM_BOT_TOKEN}
      webhook-base-url: ${TELEGRAM_BOT_WEBHOOK_URL}
      webhook-path: /api/telegram/updates
  geonames:
    username: ${GEONAMES_USERNAME}
    base-url: ${GEONAMES_BASE_URL}
  nominatim:
    base-url: ${NOMINATIM_BASE_URL}
    user-agent-header-value: ${USER_AGENT_HEADER_VALUE}

server:
  shutdown: graceful
  port: 8080
  servlet:
    context-path: /bot
  tomcat:
    connection-timeout: ${app.connection-timeout}

spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: ${app.shutdown-timeout}s

  application:
    name: astro-business-service
    version: @project.version@

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${app.postgres.schema}
    database-change-log-table: business_service_changelog
    database-change-log-lock-table: business_service_changeloglock
    liquibase-schema: public

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: ${app.postgres.schema}
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true

  datasource:
    url: ${app.postgres.url}
    username: ${app.postgres.username}
    password: ${app.postgres.password}
    hikari:
      maxLifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 10
      connectionTimeout: 30000
      idleTimeout: 300000
      leakDetectionThreshold: 10000
      initializationFailTimeout: 10000
      validationTimeout: 5000
      connection-test-query: SELECT 1
      keepalive-time: 30000

springdoc:
  packagesToScan: com.spuzakov.astro.astrobusinessservice.controller
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints.web.exposure.include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: ALWAYS
      probes.enabled: true

logging:
  level:
    com.spuzakov.astro: ${APP_LOG_LEVEL:DEBUG}
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

